#!/bin/sh

set -e

. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # Create the default configuration.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.unionfilesystems"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.unionfilesystems" "$2"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
