#!/bin/sh

set -e

case "$1" in
    purge)
        echo "Cleaning up configuration database ..."
        omv-confdbadm delete "conf.service.unionfilesystems"
    ;;

    remove|upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
